# frozen_string_literal: true

source "https://rubygems.org"

ruby file: ".ruby-version"

gem "rails", "6.0.6.1"

gem "bootsnap", ">= 1.4.2", require: false
gem "puma", "~> 4.1"

gem "sidekiq" # added to test skipping mounted applications

group :development, :test do
  gem "pry-byebug"
  gem "rspec-rails"
  gem "rswag-specs"
  gem "simplecov"
  gem "swagcov", path: "../.."
end

gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]
