# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "2.7.8"

gem "rails", "6.0.6.1"

gem "bootsnap", ">= 1.4.2", require: false
gem "puma", "~> 4.1"

group :development, :test do
  gem "pry-byebug"
  gem "rspec-rails"
  gem "rswag-specs"
  gem "swagcov", path: "../.."
end

gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]
