plugins:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rake
  - rubocop-thread_safety

AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
  Exclude:
    - '**/bin/*'
    - vendor/bundle/**/* # https://github.com/rubocop/rubocop/issues/9832#issuecomment-882111229

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - '**/spec/tasks/**/*'
    - '**/spec/requests/**/*'
    - '**/exe/**/*'

RSpec/ExampleLength:
  Enabled: false

RSpec/EmptyExampleGroup:
  Exclude:
    - '**/requests/**/*' # due to using rswag in sandbox applications

Style/Documentation:
  Enabled: false

Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120
