# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5c389d5f91824bc69c72c93b388fe01aded8d02c90f31b8ef71f4dc1df4278d2957f31443b834e324401ce88b41ae50f4bd322d476b3eb14e79f007cf9417929

test:
  secret_key_base: 2a71935419d80d022a5266fda74af2b921b6a225f9286e95623096ff9218d0d3e5b34fd849850ea0bef6596e1435e62bcc7849bab1ac6128a8610bf9b3e87950

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
