# frozen_string_literal: true

source "https://rubygems.org"

ruby file: ".ruby-version"

gem "rails", "7.0.8.7"

gem "bootsnap", require: false
gem "puma", ">= 5.0"
gem "tzinfo-data", platforms: %i[windows jruby]

group :development, :test do
  gem "pry-byebug"
  gem "rspec-rails"
  gem "rswag-specs"
  gem "simplecov"
  gem "swagcov", path: "../.."
end
