# frozen_string_literal: true

source "https://rubygems.org"

ruby file: ".ruby-version"

gem "rails", "8.0.2.1"

gem "bootsnap", require: false
gem "puma", ">= 5.0"
gem "tzinfo-data", platforms: %i[windows jruby]

gem "turbo-rails" # added to test skipping turbo related routes (system tests will catch)

group :development, :test do
  gem "pry-byebug"
  gem "rb-readline" # for pry on ruby 3.5
  gem "rspec-rails"
  gem "rswag-specs"
  gem "simplecov"
  gem "swagcov", path: "../.."
end
