# frozen_string_literal: true

source "https://rubygems.org"

ruby "3.2.7"

gem "rails", "8.0.2"

gem "bootsnap", require: false
gem "puma", ">= 5.0"
gem "tzinfo-data", platforms: %i[windows jruby]

# Deploy this application anywhere as a Docker container [https://kamal-deploy.org]
gem "kamal", require: false

# Add HTTP asset caching/compression and X-Sendfile acceleration to Puma [https://github.com/basecamp/thruster/]
gem "thruster", require: false

group :development, :test do
  gem "pry"
  gem "pry-byebug"
  gem "rspec-rails"
  gem "rswag-specs"
  gem "swagcov", path: "../.."
end
