# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

ruby "2.5.9"

gem "rails", "5.1.7"

gem "pg", ">= 0.18", "< 2.0"
gem "puma", "~> 3.7"

# resolve loading error
gem "multi_json"

group :development, :test do
  gem "database_cleaner"
  gem "pry"
  gem "pry-byebug"
  gem "rspec-rails"
  gem "rswag-specs"
  gem "swagcov", path: "../.."
end

group :development do
  gem "listen", ">= 3.0.5", "< 3.2"
  gem "spring"
  gem "spring-watcher-listen", "~> 2.0.0"
end

gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]
