# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

ruby "2.6.10"

gem "rails", "5.1.7"

gem "puma", "~> 3.7"

# resolve loading error
gem "multi_json"

group :development, :test do
  gem "rspec-rails"
  gem "rswag-specs", "2.11.0" # Fix FrozenError: can't modify frozen Hash & ignore deprecation outside of project scope
  gem "simplecov"
  gem "swagcov", path: "../.."
end

gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]
