# frozen_string_literal: true

source "https://rubygems.org"

ruby file: ".ruby-version"

gem "rails", "5.1.7"

gem "puma", "~> 3.7"

# resolve loading error
gem "multi_json"

gem "sidekiq" # added to test skipping mounted applications

group :development, :test do
  gem "rspec-rails"
  gem "rswag-specs", "2.11.0" # silence deprecations with older version + application.rb config
  gem "simplecov"
  gem "swagcov", path: "../.."
end

gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]
