# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.1.7"

gem "rails", "6.1.7.10"

gem "bootsnap", ">= 1.4.4", require: false
gem "puma", "~> 5.0"

group :development, :test do
  gem "pry-byebug"
  gem "rspec-rails"
  gem "rswag-specs"
  gem "simplecov"
  gem "swagcov", path: "../.."
end

gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]
