# frozen_string_literal: true

source "https://rubygems.org"

ruby file: ".ruby-version"

gem "rails", "5.2.8.1"

gem "bootsnap", ">= 1.1.0", require: false
gem "puma"

group :development, :test do
  gem "rspec-rails"
  gem "rswag-specs"
  gem "simplecov"
  gem "swagcov", path: "../.."
end

gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]
