# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "2.7.8"

gem "rails", "5.2.8.1"

gem "bootsnap", ">= 1.1.0", require: false
gem "puma"

# resolve loading error
gem "multi_json"

group :development, :test do
  gem "pry-byebug"
  gem "rspec-rails"
  gem "rswag-specs"
  gem "simplecov"
  gem "swagcov", path: "../.."
end

gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]
