# This workflow runs units tests

name: Rails Latest Base Specs
on: [push]

jobs:
  test:
    name: Ruby ${{ matrix.ruby-version }} / ${{ matrix.gemfile }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['3.2', '3.3', '3.4']
        gemfile:
          - gemfiles/rails_8_0
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          rubygems: 'latest' # resolve warnings for older ruby versions
          bundler-cache: true
          cache-version: 1
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rspec spec --exclude-pattern spec/sandbox_**/**/*_spec.rb
