# This workflow runs units tests

name: Base Specs
on: [push, pull_request]

jobs:
  test:
    name: Ruby ${{ matrix.ruby-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['2.6', '2.7', '3.0', '3.1', '3.2']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          rubygems: 'latest' # resolve warnings for older ruby versions
          bundler-cache: true
          cache-version: 1
      - name: Run tests
        run: bundle exec rspec spec --exclude-pattern spec/sandbox_**/**/*_spec.rb
