# This workflow runs units tests for end of life ruby versions that require a different setup for GitHub Actions

name: EOL Base Specs
on: [push]

jobs:
  test:
    name: Ruby ${{ matrix.ruby-version }} / ${{ matrix.gemfile }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['2.5', '2.6']
        gemfile:
          - gemfiles/rails_5_0
          - gemfiles/rails_5_1
          - gemfiles/rails_5_2
          - gemfiles/rails_6_0
          - gemfiles/rails_6_1
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          rubygems: 3.2.3 # resolve warnings for older ruby versions
          bundler-cache: true
          cache-version: 1
      - name: Run tests
        run: bundle exec rspec spec --exclude-pattern spec/sandbox_**/**/*_spec.rb
