name: Rubocop Linting
on: [push]

jobs:
  rubocop-lint:
    name: Rubocop
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler: "Gemfile.lock"
          rubygems: 'latest'
          bundler-cache: true
          cache-version: 1
      - name: Run Rubocop
        run: bundle exec rubocop
