# This workflow runs end to end tests from a real Rails 7.2 application located in the spec/sandbox_7_2 directory.

name: "E2E Specs"
on: [push]

jobs:
  test:
    name: Rails 7.2 / Ruby 3.1
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler: "Gemfile.lock"
          bundler-cache: true
          cache-version: 1
          working-directory: spec/sandbox_7_2
      - name: Set up database schema
        run: bundle exec rails db:migrate
        working-directory: spec/sandbox_7_2
      - name: Run tests
        run: bundle exec rspec spec
        working-directory: spec/sandbox_7_2
