# This workflow runs end to end tests from a real Rails 5.0 application located in the spec/sandbox_5_0 directory.

name: "E2E Specs"
on: [push]

jobs:
  test:
    name: Rails 5.0 / Ruby 2.5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          rubygems: 'latest'
          bundler: 'Gemfile.lock'
          bundler-cache: true
          cache-version: 1
          working-directory: spec/sandbox_5_0
      - name: Run tests
        run: bundle exec rspec spec
        working-directory: spec/sandbox_5_0
