# This workflow runs end to end tests from real rails applications located in the spec/sandbox_** directories

name: 'E2E Tests'
on: [push]

jobs:
  test:
    name: Rails ${{ matrix.sandbox }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sandbox:
          - spec/sandbox_5_0
          - spec/sandbox_5_1
          - spec/sandbox_5_2
          - spec/sandbox_6_0
          - spec/sandbox_6_1
          - spec/sandbox_7_2
          - spec/sandbox_8_0
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          rubygems: 'latest'
          bundler: 'Gemfile.lock'
          bundler-cache: true
          cache-version: 1
          working-directory: ${{ matrix.sandbox }}
      - name: Run tests
        run: bundle exec rspec spec
        working-directory: ${{ matrix.sandbox }}
