name: Tests
on: [push]

jobs:
  unit_test:
    name: Ruby ${{ matrix.ruby-version }} / ${{ matrix.gemfile }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['2.5', '2.6', '2.7', '3.0', '3.1', '3.2', '3.3', '3.4', '3.5']
        gemfile:
          - .github/gemfiles/rails_4_2
          - .github/gemfiles/rails_5_0
          - .github/gemfiles/rails_5_1
          - .github/gemfiles/rails_5_2
          - .github/gemfiles/rails_6_0
          - .github/gemfiles/rails_6_1
          - .github/gemfiles/rails_7_0
          - .github/gemfiles/rails_7_1
          - .github/gemfiles/rails_7_2
          - .github/gemfiles/rails_8_0
        exclude:
          - ruby-version: '2.5'
            gemfile: .github/gemfiles/rails_7_0 # ruby 2.7 minimum for rails 7.0
          - ruby-version: '2.5'
            gemfile: .github/gemfiles/rails_7_1 # ruby 2.7 minimum for rails 7.1
          - ruby-version: '2.5'
            gemfile: .github/gemfiles/rails_7_2 # ruby 3.1 minimum for rails 7.2
          - ruby-version: '2.5'
            gemfile: .github/gemfiles/rails_8_0 # ruby 3.2 minimum for rails 8.0
          - ruby-version: '2.6'
            gemfile: .github/gemfiles/rails_7_0 # ruby 2.7 minimum for rails 7.0
          - ruby-version: '2.6'
            gemfile: .github/gemfiles/rails_7_1 # ruby 2.7 minimum for rails 7.1
          - ruby-version: '2.6'
            gemfile: .github/gemfiles/rails_7_2 # ruby 3.1 minimum for rails 7.2
          - ruby-version: '2.6'
            gemfile: .github/gemfiles/rails_8_0 # ruby 3.2 minimum for rails 8.0
          - ruby-version: '2.7'
            gemfile: .github/gemfiles/rails_7_2 # ruby 3.1 minimum for rails 7.2
          - ruby-version: '2.7'
            gemfile: .github/gemfiles/rails_8_0 # ruby 3.2 minimum for rails 8.0
          - ruby-version: '3.0'
            gemfile: .github/gemfiles/rails_7_2 # ruby 3.1 minimum for rails 7.2
          - ruby-version: '3.0'
            gemfile: .github/gemfiles/rails_8_0 # ruby 3.2 minimum for rails 8.0
          - ruby-version: '3.1'
            gemfile: .github/gemfiles/rails_8_0 # ruby 3.2 minimum for rails 8.0
          - ruby-version: '3.2'
            gemfile: .github/gemfiles/rails_4_2 # bundler < 2 needed
          - ruby-version: '3.3'
            gemfile: .github/gemfiles/rails_4_2 # bundler < 2 needed
          - ruby-version: '3.4'
            gemfile: .github/gemfiles/rails_4_2 # bundler < 2 needed
          - ruby-version: '3.5'
            gemfile: .github/gemfiles/rails_4_2 # bundler < 2 needed

    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Ruby (rails 4.2)
        if: ${{ matrix.gemfile == 'gemfiles/rails_4_2' }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler: 1.17.3
          bundler-cache: true
          cache-version: 1
      - name: Setup Ruby
        if: ${{ matrix.gemfile != 'gemfiles/rails_4_2' }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          rubygems: 'latest'
          bundler-cache: true
          cache-version: 1
      - name: Run tests
        run: bundle exec rspec
      - name: Coveralls Parallel
        uses: coverallsapp/github-action@v2
        with:
          flag-name: run-${{ join(matrix.*, '-') }}
          parallel: true

  e2e_test:
    name: Rails ${{ matrix.sandbox }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sandbox:
          - spec/sandbox_4_2
          - spec/sandbox_5_0
          - spec/sandbox_5_1
          - spec/sandbox_5_2
          - spec/sandbox_6_0
          - spec/sandbox_6_1
          - spec/sandbox_7_0
          - spec/sandbox_7_1
          - spec/sandbox_7_2
          - spec/sandbox_8_0
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          rubygems: 'latest'
          bundler: 'Gemfile.lock'
          bundler-cache: true
          cache-version: 1
          working-directory: ${{ matrix.sandbox }}
      - name: Run tests
        run: bundle exec rspec spec
        working-directory: ${{ matrix.sandbox }}
      - name: Coveralls Parallel
        uses: coverallsapp/github-action@v2
        with:
          flag-name: run-${{ join(matrix.*, '-') }}
          parallel: true

  finish:
    needs: [unit_test, e2e_test]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@v2
      with:
        parallel-finished: true
        carryforward: "run-1,run-2"
