name: Unit Tests
on: [push]

jobs:
  test:
    name: Ruby ${{ matrix.ruby-version }} / ${{ matrix.gemfile }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['2.5', '2.6', '2.7', '3.0', '3.1', '3.2', '3.3', '3.4']
        gemfile:
          - gemfiles/rails_5_0
          - gemfiles/rails_5_1
          - gemfiles/rails_5_2
          - gemfiles/rails_6_0
          - gemfiles/rails_6_1
          - gemfiles/rails_7_0
          - gemfiles/rails_7_1
          - gemfiles/rails_7_2
          - gemfiles/rails_8_0
        exclude:
          - ruby-version: '2.5'
            gemfile: gemfiles/rails_7_0 # ruby 2.7 minimum for rails 7.0
          - ruby-version: '2.5'
            gemfile: gemfiles/rails_7_1 # ruby 2.7 minimum for rails 7.1
          - ruby-version: '2.5'
            gemfile: gemfiles/rails_7_2 # ruby 3.1 minimum for rails 7.2
          - ruby-version: '2.5'
            gemfile: gemfiles/rails_8_0 # ruby 3.2 minimum for rails 8.0
          - ruby-version: '2.6'
            gemfile: gemfiles/rails_7_0 # ruby 2.7 minimum for rails 7.0
          - ruby-version: '2.6'
            gemfile: gemfiles/rails_7_1 # ruby 2.7 minimum for rails 7.1
          - ruby-version: '2.6'
            gemfile: gemfiles/rails_7_2 # ruby 3.1 minimum for rails 7.2
          - ruby-version: '2.6'
            gemfile: gemfiles/rails_8_0 # ruby 3.2 minimum for rails 8.0
          - ruby-version: '2.7'
            gemfile: gemfiles/rails_7_2 # ruby 3.1 minimum for rails 7.2
          - ruby-version: '2.7'
            gemfile: gemfiles/rails_8_0 # ruby 3.2 minimum for rails 8.0
          - ruby-version: '3.0'
            gemfile: gemfiles/rails_7_2 # ruby 3.1 minimum for rails 7.2
          - ruby-version: '3.0'
            gemfile: gemfiles/rails_8_0 # ruby 3.2 minimum for rails 8.0
          - ruby-version: '3.1'
            gemfile: gemfiles/rails_8_0 # ruby 3.2 minimum for rails 8.0
          - ruby-version: '3.4'
            gemfile: gemfiles/rails_5_0
          - ruby-version: '3.4'
            gemfile: gemfiles/rails_5_1
          - ruby-version: '3.4'
            gemfile: gemfiles/rails_5_2

    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          rubygems: 'latest'
          bundler-cache: true
          cache-version: 1
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rspec spec --exclude-pattern spec/sandbox_**/**/*_spec.rb
